# Home work 1

In [1]:
# presetings
import numpy as np

1. Create a one-dimensional array (vector) with the first 10 natural numbers and output its value.

In [2]:
vector1 = np.arange(1, 11)

print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 3x3 two-dimensional array (matrix), fill it with zeros, and output its values.

In [3]:
matrix1 = np.zeros((3, 3))
print("\n", matrix1)


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 5x5 array, fill it with random integers from 1 to 10, and output its value.

In [4]:
matrix2 = np.random.randint(1, 11, size=(5, 5))
print("\n", matrix2)


 [[ 8  9 10  3  7]
 [ 5  4  6  8  8]
 [ 9  3 10  1  6]
 [ 3 10  2  6  7]
 [ 7  4  4  4  9]]


4. Create a 4x4 array, fill it with random real numbers in the range 0 to 1, and output its value.

In [5]:
matrix3 = np.random.rand(4, 4)
print(matrix3)


 [[0.4068092  0.09673505 0.06892999 0.41965735]
 [0.14496147 0.19750458 0.88179608 0.62317844]
 [0.46434615 0.92057001 0.97153769 0.0015101 ]
 [0.13860206 0.50076622 0.65794431 0.44047802]]


5. Create two one-dimensional arrays of size 5, fill them with random integers from 1 to 10, and perform element-by-element addition, subtraction, and multiplication operations on them.

In [23]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("\n", "First vector:", array1)
print("Second vector:", array2)
print("      Vectors addition:", array1 + array2)
print("   Vectors subtraction:", array1 - array2)
print("Vectors multiplication:", array1 * array2)


 First vector: [10  6  6  5  8]
Second vector: [ 4 10  3  1  3]
      Vectors addition: [14 16  9  6 11]
   Vectors subtraction: [ 6 -4  3  4  5]
Vectors multiplication: [40 60 18  5 24]


6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [25]:
vector2 = np.random.rand(7)
vector3 = np.random.rand(7)
dot_product = np.dot(vector2, vector3)
print("\n", "First vector:")
print(vector2)
print("Second vector:")
print(vector3)
print("Scalar product:", dot_product)


 First vector:
[0.96024239 0.53110603 0.98983358 0.27924651 0.61263928 0.89452875
 0.56263874]
Second vector:
[0.94167173 0.48842107 0.74644563 0.06675678 0.72568031 0.93624213
 0.40207859]
Scalar product: 3.4294357847593413


7. Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

In [26]:
matrix4 = np.random.randint(1, 11, size=(2, 2))
matrix5 = np.random.randint(1, 11, size=(2, 3))

matrix_product = np.dot(matrix4, matrix5)
print("\n", "First matrix 2x2:")
print(matrix4)
print("Second matrix 2x3:")
print(matrix5)
print("Multiplation matrix:")
print(matrix_product)


 First matrix 2x2:
[[2 6]
 [4 1]]
Second matrix 2x3:
[[10  1  1]
 [ 1  5  3]]
Multiplation matrix:
[[26 32 20]
 [41  9  7]]


8. Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

In [32]:
matrix6 = np.random.randint(1, 11, size=(3, 3))

inverse_matrix = np.linalg.inv(matrix6)
print("\n", "Matrix:")
print(matrix6)
print("Inverse matrix:")
print(inverse_matrix)


 Matrix:
[[1 1 4]
 [2 4 4]
 [3 5 6]]
Inverse matrix:
[[-1.  -3.5  3. ]
 [ 0.   1.5 -1. ]
 [ 0.5  0.5 -0.5]]


9. Create a 4x4 matrix, fill it with random real numbers between 0 and 1, and transpose it.

In [33]:
matrix7 = np.random.rand(4, 4)

transposed_matrix = np.transpose(matrix7)
print("\n", "Matrix:")
print(matrix7)
print("Transposed matrix:")
print(transposed_matrix)


 Matrix:
[[0.16918364 0.79532091 0.42851998 0.67140243]
 [0.11905761 0.74215989 0.19470162 0.65461289]
 [0.71515329 0.02294968 0.54070978 0.90096984]
 [0.5251181  0.04077578 0.54816176 0.84146189]]
Transposed matrix:
[[0.16918364 0.11905761 0.71515329 0.5251181 ]
 [0.79532091 0.74215989 0.02294968 0.04077578]
 [0.42851998 0.19470162 0.54070978 0.54816176]
 [0.67140243 0.65461289 0.90096984 0.84146189]]


10. Create a 3x4 matrix and a vector with 4 shape, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

In [34]:
matrix8 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)

result_vector = np.dot(matrix8, vector4)
print("\n", "Matrix:")
print(matrix8)
print("Vector:")
print(vector4)
print("Result:")
print(result_vector)


 Matrix:
[[ 9  3  3  8]
 [ 3  9  8  1]
 [ 8  1  3 10]]
Vector:
[2 2 4 5]
Result:
[76 61 80]


11. Create a 2x3 matrix and a 3 vector, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

In [35]:
matrix9 = np.random.rand(2, 3)
vector5 = np.random.rand(3)

result_vector2 = np.dot(matrix9, vector5)
print("\n", "Matrix:")
print(matrix9)
print("Vecto:")
print(vector5)
print("Result:")
print(result_vector2)


 Matrix:
[[0.22090105 0.88938481 0.94119613]
 [0.74447738 0.45663466 0.85305731]]
Vecto:
[0.77708611 0.9584567  0.89325085]
Result:
[1.86482022 1.77818174]


12. Create two 2x2 matrices, fill them with random integers between 1 and 10, and multiply them elementwise.

In [36]:
matrix10 = np.random.randint(1, 11, size=(2, 2))
matrix11 = np.random.randint(1, 11, size=(2, 2))

elementwise_multiplication = np.multiply(matrix10, matrix11)
print("\n", "First matrix:")
print(matrix10)
print("Second matrix:")
print(matrix11)
print("Result:")
print(elementwise_multiplication)


 First matrix:
[[10  5]
 [ 3  6]]
Second matrix:
[[5 9]
 [6 2]]
Result:
[[50 45]
 [18 12]]


13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and find their product.

In [37]:
matrix_product2 = np.dot(matrix10, matrix11)
print("\n", "First matrix:")
print(matrix10)
print("Second matrix:")
print(matrix11)
print("Result:")
print(matrix_product2)


 First matrix:
[[10  5]
 [ 3  6]]
Second matrix:
[[5 9]
 [6 2]]
Result:
[[ 80 100]
 [ 51  39]]


14. Create a 5x5 matrix, fill it with random integers between 1 and 100, and find the sum of the matrix elements.

In [39]:
matrix12 = np.random.randint(1, 101, size=(5, 5))

sum_of_elements = np.sum(matrix12)
print("\n", "Matrix:")
print(matrix12)
print("Sum:", sum_of_elements)


 Matrix:
[[42 97  2 48 13]
 [30  3 30 83 97]
 [37 14 12 72 22]
 [39 99 58 13 81]
 [75 67 22 11 55]]
Sum: 1122


15. Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

In [41]:
matrix13 = np.random.randint(1, 11, size=(4, 4))
matrix14 = np.random.randint(1, 11, size=(4, 4))

matrix_difference = matrix13 - matrix14
print("\n", "First matrix:")
print(matrix13)
print("Second matrix:")
print(matrix14)
print("Difference:")
print(matrix_difference)


 First matrix:
[[ 9  5  7  5]
 [ 7  2  4  5]
 [ 6  1 10  3]
 [ 1  5  3  5]]
Second matrix:
[[6 5 2 5]
 [3 7 7 9]
 [6 6 4 2]
 [5 7 2 6]]
Difference:
[[ 3  0  5  0]
 [ 4 -5 -3 -4]
 [ 0 -5  6  1]
 [-4 -2  1 -1]]


16. Create a 3x3 matrix, fill it with random real numbers in the range 0 to 1, and find a column vector containing the sum of the elements of each row of the matrix.

In [44]:
matrix15 = np.random.rand(3, 3)

sum_rows = np.sum(matrix15, axis=1)
print("\n", "Matrix:")
print(matrix15)
print("Sum:")
print(sum_rows)


 Matrix:
[[0.16229476 0.37347925 0.0609255 ]
 [0.71953881 0.12813244 0.35436186]
 [0.58296611 0.24053111 0.66378388]]
Sum:
[0.59669951 1.20203311 1.4872811 ]


17. Create a 3x4 matrix of arbitrary integers and create a matrix of the squares of those numbers.

In [46]:
matrix16 = np.random.randint(1, 11, size=(3, 4))

squared_matrix = matrix16 ** 2
print("\n", "Matrix:")
print(matrix16)
print("Squared matrix:")
print(squared_matrix)


 Matrix:
[[2 3 6 8]
 [7 9 2 3]
 [1 4 3 4]]
Squared matrix:
[[ 4  9 36 64]
 [49 81  4  9]
 [ 1 16  9 16]]


18. Create a vector of size 4, fill it with random integers between 1 and 50, and find the square root vector of those numbers.

In [48]:
vector6 = np.random.randint(1, 51, size=4)

squared_vector = np.sqrt(vector6)
print("\n", "Vector:")
print(vector6)
print("Squered vector:")
print(squared_vector)


 Vector:
[25 36 26  9]
Squered vector:
[5.         6.         5.09901951 3.        ]
