# Home work 1

In [1]:
# presetings
import numpy as np

1. Create a one-dimensional array (vector) with the first 10 natural numbers and output its value.

In [2]:
vector1 = np.arange(1, 11)

print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 3x3 two-dimensional array (matrix), fill it with zeros, and output its values.

In [3]:
matrix1 = np.zeros((3, 3))
print("\n", matrix1)


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 5x5 array, fill it with random integers from 1 to 10, and output its value.

In [4]:
matrix2 = np.random.randint(1, 11, size=(5, 5))
print("\n", matrix2)


 [[ 8  9 10  3  7]
 [ 5  4  6  8  8]
 [ 9  3 10  1  6]
 [ 3 10  2  6  7]
 [ 7  4  4  4  9]]


4. Create a 4x4 array, fill it with random real numbers in the range 0 to 1, and output its value.

In [5]:
matrix3 = np.random.rand(4, 4)
print(matrix3)


 [[0.4068092  0.09673505 0.06892999 0.41965735]
 [0.14496147 0.19750458 0.88179608 0.62317844]
 [0.46434615 0.92057001 0.97153769 0.0015101 ]
 [0.13860206 0.50076622 0.65794431 0.44047802]]


5. Create two one-dimensional arrays of size 5, fill them with random integers from 1 to 10, and perform element-by-element addition, subtraction, and multiplication operations on them.

In [17]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("\n", " First vector:", array1,
      "\n", "Second vector:", array2,
      "\n",
      "\n", "      Vectors addition:", array1 + array2,
      "\n", "   Vectors subtraction:", array1 - array2,
      "\n", "Vectors multiplication:", array1 * array2)


  First vector: [ 7 10  8  2  9] 
 Second vector: [4 3 5 5 3] 
 
       Vectors addition: [11 13 13  7 12] 
    Vectors subtraction: [ 3  7  3 -3  6] 
 Vectors multiplication: [28 30 40 10 27]


6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [19]:
vector2 = np.random.rand(7)
vector3 = np.random.rand(7)
dot_product = np.dot(vector2, vector3)
print("\n", " First vector:", "\n", vector2,
      "\n", "Second vector:", "\n", vector3,
      "\n", "Scalar product:", dot_product)


  First vector: 
 [0.38543635 0.20681322 0.42878485 0.32419714 0.37501984 0.1216553
 0.46981232] 
 Second vector: 
 [0.00797697 0.61486294 0.94166138 0.73193622 0.64174868 0.64832885
 0.96016532] 
 Scalar product: 1.5419367976198168


7. Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

8. Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

9. Create a 4x4 matrix, fill it with random real numbers between 0 and 1, and transpose it.

10. Create a 3x4 matrix and a 4 vector, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

11. Create a 2x3 matrix and a 3 vector, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

12. Create two 2x2 matrices, fill them with random integers between 1 and 10, and multiply them elementwise.

13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and find their product.

14. Create a 5x5 matrix, fill it with random integers between 1 and 100, and find the sum of the matrix elements.

15. Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

16. Create a 3x3 matrix, fill it with random real numbers in the range 0 to 1, and find a column vector containing the sum of the elements of each row of the matrix.

17. Create a 3x4 matrix of arbitrary integers and create a matrix of the squares of those numbers.

18. Create a vector of size 4, fill it with random integers between 1 and 50, and find the square root vector of those numbers.