# Home work 1

In [1]:
# presetings
import numpy as np

1. Create a one-dimensional array (vector) with the first 10 natural numbers and output its value.

In [2]:
vector1 = np.arange(1, 11)

print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 3x3 two-dimensional array (matrix), fill it with zeros, and output its values.

In [3]:
matrix1 = np.zeros((3, 3))
print("\n", matrix1)


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 5x5 array, fill it with random integers from 1 to 10, and output its value.

In [4]:
matrix2 = np.random.randint(1, 11, size=(5, 5))
print("\n", matrix2)


 [[ 8  9 10  3  7]
 [ 5  4  6  8  8]
 [ 9  3 10  1  6]
 [ 3 10  2  6  7]
 [ 7  4  4  4  9]]


4. Create a 4x4 array, fill it with random real numbers in the range 0 to 1, and output its value.

In [5]:
matrix3 = np.random.rand(4, 4)
print(matrix3)


 [[0.4068092  0.09673505 0.06892999 0.41965735]
 [0.14496147 0.19750458 0.88179608 0.62317844]
 [0.46434615 0.92057001 0.97153769 0.0015101 ]
 [0.13860206 0.50076622 0.65794431 0.44047802]]


5. Create two one-dimensional arrays of size 5, fill them with random integers from 1 to 10, and perform element-by-element addition, subtraction, and multiplication operations on them.

In [23]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("\n", "First vector:", array1)
print("Second vector:", array2)
print("      Vectors addition:", array1 + array2)
print("   Vectors subtraction:", array1 - array2)
print("Vectors multiplication:", array1 * array2)


 First vector: [10  6  6  5  8]
Second vector: [ 4 10  3  1  3]
      Vectors addition: [14 16  9  6 11]
   Vectors subtraction: [ 6 -4  3  4  5]
Vectors multiplication: [40 60 18  5 24]


6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [49]:
vector2 = np.random.rand(7)
vector3 = np.random.rand(7)
dot_product = np.dot(vector2, vector3)
print("\n", "First vector:")
print(vector2)
print("\n", "Second vector:")
print(vector3)
print("\n", "Scalar product:", dot_product)


 First vector:
[0.1640456  0.78369562 0.20697548 0.29587044 0.76578604 0.40272524
 0.42398781]

 Second vector:
[0.38437638 0.01460583 0.60306413 0.10234906 0.5642213  0.70388875
 0.62745212]

 Scalar product: 1.2111819370065509


7. Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

In [50]:
matrix4 = np.random.randint(1, 11, size=(2, 2))
matrix5 = np.random.randint(1, 11, size=(2, 3))

matrix_product = np.dot(matrix4, matrix5)
print("\n", "First matrix 2x2:")
print(matrix4)
print("\n", "Second matrix 2x3:")
print(matrix5)
print("\n", "Multiplation matrix:")
print(matrix_product)


 First matrix 2x2:
[[4 3]
 [5 6]]

 Second matrix 2x3:
[[ 7  9  3]
 [ 3  9 10]]

 Multiplation matrix:
[[37 63 42]
 [53 99 75]]


8. Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

In [51]:
matrix6 = np.random.randint(1, 11, size=(3, 3))

inverse_matrix = np.linalg.inv(matrix6)
print("\n", "Matrix:")
print(matrix6)
print("\n", "Inverse matrix:")
print(inverse_matrix)


 Matrix:
[[2 9 4]
 [1 1 6]
 [7 3 8]]

 Inverse matrix:
[[-0.03703704 -0.22222222  0.18518519]
 [ 0.12592593 -0.04444444 -0.02962963]
 [-0.01481481  0.21111111 -0.02592593]]


9. Create a 4x4 matrix, fill it with random real numbers between 0 and 1, and transpose it.

In [52]:
matrix7 = np.random.rand(4, 4)

transposed_matrix = np.transpose(matrix7)
print("\n", "Matrix:")
print(matrix7)
print("\n", "Transposed matrix:")
print(transposed_matrix)


 Matrix:
[[0.06325767 0.65027982 0.72832845 0.60372226]
 [0.24285885 0.0129205  0.3184784  0.58023028]
 [0.40386772 0.28856859 0.42230172 0.87888175]
 [0.19891189 0.66112192 0.23134441 0.09288225]]

 Transposed matrix:
[[0.06325767 0.24285885 0.40386772 0.19891189]
 [0.65027982 0.0129205  0.28856859 0.66112192]
 [0.72832845 0.3184784  0.42230172 0.23134441]
 [0.60372226 0.58023028 0.87888175 0.09288225]]


10. Create a 3x4 matrix and a vector with 4 shape, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

In [53]:
matrix8 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)

result_vector = np.dot(matrix8, vector4)
print("\n", "Matrix:")
print(matrix8)
print("\n", "Vector:")
print(vector4)
print("\n", "Result:")
print(result_vector)


 Matrix:
[[ 1  3  6  7]
 [ 5  9  6  1]
 [ 3  9 10  7]]

 Vector:
[7 4 5 9]

 Result:
[112 110 170]


11. Create a 2x3 matrix and a 3 vector, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

In [54]:
matrix9 = np.random.rand(2, 3)
vector5 = np.random.rand(3)

result_vector2 = np.dot(matrix9, vector5)
print("\n", "Matrix:")
print(matrix9)
print("\n", "Vecto:")
print(vector5)
print("\n", "Result:")
print(result_vector2)


 Matrix:
[[0.44883662 0.38082151 0.35962062]
 [0.70004605 0.89761191 0.21722139]]

 Vecto:
[0.48680742 0.46620243 0.87788483]

 Result:
[0.7117424  0.94995183]


12. Create two 2x2 matrices, fill them with random integers between 1 and 10, and multiply them elementwise.

In [55]:
matrix10 = np.random.randint(1, 11, size=(2, 2))
matrix11 = np.random.randint(1, 11, size=(2, 2))

elementwise_multiplication = np.multiply(matrix10, matrix11)
print("\n", "First matrix:")
print(matrix10)
print("\n", "Second matrix:")
print(matrix11)
print("\n", "Result:")
print(elementwise_multiplication)


 First matrix:
[[1 3]
 [2 7]]

 Second matrix:
[[2 8]
 [3 1]]

 Result:
[[ 2 24]
 [ 6  7]]


13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and find their product.

In [56]:
matrix_product2 = np.dot(matrix10, matrix11)
print("\n", "First matrix:")
print(matrix10)
print("\n", "Second matrix:")
print(matrix11)
print("\n", "Result:")
print(matrix_product2)


 First matrix:
[[1 3]
 [2 7]]

 Second matrix:
[[2 8]
 [3 1]]

 Result:
[[11 11]
 [25 23]]


14. Create a 5x5 matrix, fill it with random integers between 1 and 100, and find the sum of the matrix elements.

In [57]:
matrix12 = np.random.randint(1, 101, size=(5, 5))

sum_of_elements = np.sum(matrix12)
print("\n", "Matrix:")
print(matrix12)
print("\n", "Sum:", sum_of_elements)


 Matrix:
[[81 67 76 95 23]
 [37 22 26 37 69]
 [76 75 46 23 32]
 [41 32 65  6 60]
 [ 6 94 42 83  1]]

 Sum: 1215


15. Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

In [58]:
matrix13 = np.random.randint(1, 11, size=(4, 4))
matrix14 = np.random.randint(1, 11, size=(4, 4))

matrix_difference = matrix13 - matrix14
print("\n", "First matrix:")
print(matrix13)
print("\n", "Second matrix:")
print(matrix14)
print("\n", "Difference:")
print(matrix_difference)


 First matrix:
[[10  3  4  4]
 [ 6  1 10  3]
 [ 7  7  6  1]
 [ 3  6  1  4]]

 Second matrix:
[[ 8  3  8  1]
 [ 7  9  8  6]
 [ 9  9  5 10]
 [ 8  6  7  3]]

 Difference:
[[ 2  0 -4  3]
 [-1 -8  2 -3]
 [-2 -2  1 -9]
 [-5  0 -6  1]]


16. Create a 3x3 matrix, fill it with random real numbers in the range 0 to 1, and find a column vector containing the sum of the elements of each row of the matrix.

In [59]:
matrix15 = np.random.rand(3, 3)

sum_rows = np.sum(matrix15, axis=1)
print("\n", "Matrix:")
print(matrix15)
print("\n", "Sum:")
print(sum_rows)


 Matrix:
[[0.8825397  0.29599291 0.80759312]
 [0.39899157 0.01661267 0.56123919]
 [0.15453441 0.74794501 0.87493907]]

 Sum:
[1.98612573 0.97684342 1.77741849]


17. Create a 3x4 matrix of arbitrary integers and create a matrix of the squares of those numbers.

In [60]:
matrix16 = np.random.randint(1, 11, size=(3, 4))

squared_matrix = matrix16 ** 2
print("\n", "Matrix:")
print(matrix16)
print("\n", "Squared matrix:")
print(squared_matrix)


 Matrix:
[[ 1  9  6  1]
 [ 2 10  7  4]
 [ 8  1  9 10]]

 Squared matrix:
[[  1  81  36   1]
 [  4 100  49  16]
 [ 64   1  81 100]]


18. Create a vector of size 4, fill it with random integers between 1 and 50, and find the square root vector of those numbers.

In [61]:
vector6 = np.random.randint(1, 51, size=4)

squared_vector = np.sqrt(vector6)
print("\n", "Vector:")
print(vector6)
print("\n", "Squered vector:")
print(squared_vector)


 Vector:
[22 42 34 47]

 Squered vector:
[4.69041576 6.4807407  5.83095189 6.8556546 ]
